### ISSUE TITLE
License?!?

### ISSUE THREAD

**Issue by micwin** [mrcritical/ironcache#6]
Heyho,

afaik there is no license file nor a license entry in the pom, so my question: what license?

Could you please add a licenses entry to the pom OR a LICENSE file to the repository?!?

Would highly appreciate GPL or MIT.

**Comment by mrcritical** [comment]
Sure, I will add an MIT license.

**Comment by mrcritical** [comment]
I added the MIT license to both the pom and source code. I released 2.0.1 which includes it.

**Comment by micwin** [comment]
thx a lot
